export const PHONECODES = [{"countryCode":"DZ", "phoneCode":"213","country" :"Algeria (+213)"},
{"countryCode":"AD", "phoneCode":"376","country" :"Andorra (+376)"},
{"countryCode":"AO", "phoneCode":"244","country" :"Angola (+244)"},
{"countryCode":"AI", "phoneCode":"1264","country" :"Anguilla (+1264)"},
{"countryCode":"AG", "phoneCode":"1268","country" :"Antigua &amp; Barbuda (+1268)"},
{"countryCode":"AR", "phoneCode":"54","country" :"Argentina (+54)"},
{"countryCode":"AM", "phoneCode":"374","country" :"Armenia (+374)"},
{"countryCode":"AW", "phoneCode":"297","country" :"Aruba (+297)"},
{"countryCode":"AU", "phoneCode":"61","country" :"Australia (+61)"},
{"countryCode":"AT", "phoneCode":"43","country" :"Austria (+43)"},
{"countryCode":"AZ", "phoneCode":"994","country" :"Azerbaijan (+994)"},
{"countryCode":"BS", "phoneCode":"1242","country" :"Bahamas (+1242)"},
{"countryCode":"BH", "phoneCode":"973","country" :"Bahrain (+973)"},
{"countryCode":"BD", "phoneCode":"880","country" :"Bangladesh (+880)"},
{"countryCode":"BB", "phoneCode":"1246","country" :"Barbados (+1246)"},
{"countryCode":"BY", "phoneCode":"375","country" :"Belarus (+375)"},
{"countryCode":"BE", "phoneCode":"32","country" :"Belgium (+32)"},
{"countryCode":"BZ", "phoneCode":"501","country" :"Belize (+501)"},
{"countryCode":"BJ", "phoneCode":"229","country" :"Benin (+229)"},
{"countryCode":"BM", "phoneCode":"1441","country" :"Bermuda (+1441)"},
{"countryCode":"BT", "phoneCode":"975","country" :"Bhutan (+975)"},
{"countryCode":"BO", "phoneCode":"591","country" :"Bolivia (+591)"},
{"countryCode":"BA", "phoneCode":"387","country" :"Bosnia Herzegovina (+387)"},
{"countryCode":"BW", "phoneCode":"267","country" :"Botswana (+267)"},
{"countryCode":"BR", "phoneCode":"55","country" :"Brazil (+55)"},
{"countryCode":"BN", "phoneCode":"673","country" :"Brunei (+673)"},
{"countryCode":"BG", "phoneCode":"359","country" :"Bulgaria (+359)"},
{"countryCode":"BF", "phoneCode":"226","country" :"Burkina Faso (+226)"},
{"countryCode":"BI", "phoneCode":"257","country" :"Burundi (+257)"},
{"countryCode":"KH", "phoneCode":"855","country" :"Cambodia (+855)"},
{"countryCode":"CM", "phoneCode":"237","country" :"Cameroon (+237)"},
{"countryCode":"CA", "phoneCode":"1","country" :"Canada (+1)"},
{"countryCode":"CV", "phoneCode":"238","country" :"Cape Verde Islands (+238)"},
{"countryCode":"KY", "phoneCode":"1345","country" :"Cayman Islands (+1345)"},
{"countryCode":"CF", "phoneCode":"236","country" :"Central African Republic (+236)"},
{"countryCode":"CL", "phoneCode":"56","country" :"Chile (+56)"},
{"countryCode":"CN", "phoneCode":"86","country" :"China (+86)"},
{"countryCode":"CO", "phoneCode":"57","country" :"Colombia (+57)"},
{"countryCode":"KM", "phoneCode":"269","country" :"Comoros (+269)"},
{"countryCode":"CG", "phoneCode":"242","country" :"Congo (+242)"},
{"countryCode":"CK", "phoneCode":"682","country" :"Cook Islands (+682)"},
{"countryCode":"CR", "phoneCode":"506","country" :"Costa Rica (+506)"},
{"countryCode":"HR", "phoneCode":"385","country" :"Croatia (+385)"},
{"countryCode":"CU", "phoneCode":"53","country" :"Cuba (+53)"},
{"countryCode":"CY", "phoneCode":"90392","country" :"Cyprus North (+90392)"},
{"countryCode":"CY", "phoneCode":"357","country" :"Cyprus South (+357)"},
{"countryCode":"CZ", "phoneCode":"42","country" :"Czech Republic (+42)"},
{"countryCode":"DK", "phoneCode":"45","country" :"Denmark (+45)"},
{"countryCode":"DJ", "phoneCode":"253","country" :"Djibouti (+253)"},
{"countryCode":"DM", "phoneCode":"1809","country" :"Dominica (+1809)"},
{"countryCode":"DO", "phoneCode":"1809","country" :"Dominican Republic (+1809)"},
{"countryCode":"EC", "phoneCode":"593","country" :"Ecuador (+593)"},
{"countryCode":"EG", "phoneCode":"20","country" :"Egypt (+20)"},
{"countryCode":"SV", "phoneCode":"503","country" :"El Salvador (+503)"},
{"countryCode":"GQ", "phoneCode":"240","country" :"Equatorial Guinea (+240)"},
{"countryCode":"ER", "phoneCode":"291","country" :"Eritrea (+291)"},
{"countryCode":"EE", "phoneCode":"372","country" :"Estonia (+372)"},
{"countryCode":"ET", "phoneCode":"251","country" :"Ethiopia (+251)"},
{"countryCode":"FK", "phoneCode":"500","country" :"Falkland Islands (+500)"},
{"countryCode":"FO", "phoneCode":"298","country" :"Faroe Islands (+298)"},
{"countryCode":"FJ", "phoneCode":"679","country" :"Fiji (+679)"},
{"countryCode":"FI", "phoneCode":"358","country" :"Finland (+358)"},
{"countryCode":"FR", "phoneCode":"33","country" :"France (+33)"},
{"countryCode":"GF", "phoneCode":"594","country" :"French Guiana (+594)"},
{"countryCode":"PF", "phoneCode":"689","country" :"French Polynesia (+689)"},
{"countryCode":"GA", "phoneCode":"241","country" :"Gabon (+241)"},
{"countryCode":"GM", "phoneCode":"220","country" :"Gambia (+220)"},
{"countryCode":"GE", "phoneCode":"7880","country" :"Georgia (+7880)"},
{"countryCode":"DE", "phoneCode":"49","country" :"Germany (+49)"},
{"countryCode":"GH", "phoneCode":"233","country" :"Ghana (+233)"},
{"countryCode":"GI", "phoneCode":"350","country" :"Gibraltar (+350)"},
{"countryCode":"GR", "phoneCode":"30","country" :"Greece (+30)"},
{"countryCode":"GL", "phoneCode":"299","country" :"Greenland (+299)"},
{"countryCode":"GD", "phoneCode":"1473","country" :"Grenada (+1473)"},
{"countryCode":"GP", "phoneCode":"590","country" :"Guadeloupe (+590)"},
{"countryCode":"GU", "phoneCode":"671","country" :"Guam (+671)"},
{"countryCode":"GT", "phoneCode":"502","country" :"Guatemala (+502)"},
{"countryCode":"GN", "phoneCode":"224","country" :"Guinea (+224)"},
{"countryCode":"GW", "phoneCode":"245","country" :"Guinea - Bissau (+245)"},
{"countryCode":"GY", "phoneCode":"592","country" :"Guyana (+592)"},
{"countryCode":"HT", "phoneCode":"509","country" :"Haiti (+509)"},
{"countryCode":"HN", "phoneCode":"504","country" :"Honduras (+504)"},
{"countryCode":"HK", "phoneCode":"852","country" :"Hong Kong (+852)"},
{"countryCode":"HU", "phoneCode":"36","country" :"Hungary (+36)"},
{"countryCode":"IS", "phoneCode":"354","country" :"Iceland (+354)"},
{"countryCode":"IN", "phoneCode":"91","country" :"India (+91)"},
{"countryCode":"ID", "phoneCode":"62","country" :"Indonesia (+62)"},
{"countryCode":"IR", "phoneCode":"98","country" :"Iran (+98)"},
{"countryCode":"IQ", "phoneCode":"964","country" :"Iraq (+964)"},
{"countryCode":"IE", "phoneCode":"353","country" :"Ireland (+353)"},
{"countryCode":"IL", "phoneCode":"972","country" :"Israel (+972)"},
{"countryCode":"IT", "phoneCode":"39","country" :"Italy (+39)"},
{"countryCode":"JM", "phoneCode":"1876","country" :"Jamaica (+1876)"},
{"countryCode":"JP", "phoneCode":"81","country" :"Japan (+81)"},
{"countryCode":"JO", "phoneCode":"962","country" :"Jordan (+962)"},
{"countryCode":"KZ", "phoneCode":"7","country" :"Kazakhstan (+7)"},
{"countryCode":"KE", "phoneCode":"254","country" :"Kenya (+254)"},
{"countryCode":"KI", "phoneCode":"686","country" :"Kiribati (+686)"},
{"countryCode":"KP", "phoneCode":"850","country" :"Korea North (+850)"},
{"countryCode":"KR", "phoneCode":"82","country" :"Korea South (+82)"},
{"countryCode":"KW", "phoneCode":"965","country" :"Kuwait (+965)"},
{"countryCode":"KG", "phoneCode":"996","country" :"Kyrgyzstan (+996)"},
{"countryCode":"LA", "phoneCode":"856","country" :"Laos (+856)"},
{"countryCode":"LV", "phoneCode":"371","country" :"Latvia (+371)"},
{"countryCode":"LB", "phoneCode":"961","country" :"Lebanon (+961)"},
{"countryCode":"LS", "phoneCode":"266","country" :"Lesotho (+266)"},
{"countryCode":"LR", "phoneCode":"231","country" :"Liberia (+231)"},
{"countryCode":"LY", "phoneCode":"218","country" :"Libya (+218)"},
{"countryCode":"LI", "phoneCode":"417","country" :"Liechtenstein (+417)"},
{"countryCode":"LT", "phoneCode":"370","country" :"Lithuania (+370)"},
{"countryCode":"LU", "phoneCode":"352","country" :"Luxembourg (+352)"},
{"countryCode":"MO", "phoneCode":"853","country" :"Macao (+853)"},
{"countryCode":"MK", "phoneCode":"389","country" :"Macedonia (+389)"},
{"countryCode":"MG", "phoneCode":"261","country" :"Madagascar (+261)"},
{"countryCode":"MW", "phoneCode":"265","country" :"Malawi (+265)"},
{"countryCode":"MY", "phoneCode":"60","country" :"Malaysia (+60)"},
{"countryCode":"MV", "phoneCode":"960","country" :"Maldives (+960)"},
{"countryCode":"ML", "phoneCode":"223","country" :"Mali (+223)"},
{"countryCode":"MT", "phoneCode":"356","country" :"Malta (+356)"},
{"countryCode":"MH", "phoneCode":"692","country" :"Marshall Islands (+692)"},
{"countryCode":"MQ", "phoneCode":"596","country" :"Martinique (+596)"},
{"countryCode":"MR", "phoneCode":"222","country" :"Mauritania (+222)"},
{"countryCode":"YT", "phoneCode":"269","country" :"Mayotte (+269)"},
{"countryCode":"MX", "phoneCode":"52","country" :"Mexico (+52)"},
{"countryCode":"FM", "phoneCode":"691","country" :"Micronesia (+691)"},
{"countryCode":"MD", "phoneCode":"373","country" :"Moldova (+373)"},
{"countryCode":"MC", "phoneCode":"377","country" :"Monaco (+377)"},
{"countryCode":"MN", "phoneCode":"976","country" :"Mongolia (+976)"},
{"countryCode":"MS", "phoneCode":"1664","country" :"Montserrat (+1664)"},
{"countryCode":"MA", "phoneCode":"212","country" :"Morocco (+212)"},
{"countryCode":"MZ", "phoneCode":"258","country" :"Mozambique (+258)"},
{"countryCode":"MN", "phoneCode":"95","country" :"Myanmar (+95)"},
{"countryCode":"NA", "phoneCode":"264","country" :"Namibia (+264)"},
{"countryCode":"NR", "phoneCode":"674","country" :"Nauru (+674)"},
{"countryCode":"NP", "phoneCode":"977","country" :"Nepal (+977)"},
{"countryCode":"NL", "phoneCode":"31","country" :"Netherlands (+31)"},
{"countryCode":"NC", "phoneCode":"687","country" :"New Caledonia (+687)"},
{"countryCode":"NZ", "phoneCode":"64","country" :"New Zealand (+64)"},
{"countryCode":"NI", "phoneCode":"505","country" :"Nicaragua (+505)"},
{"countryCode":"NE", "phoneCode":"227","country" :"Niger (+227)"},
{"countryCode":"NG", "phoneCode":"234","country" :"Nigeria (+234)"},
{"countryCode":"NU", "phoneCode":"683","country" :"Niue (+683)"},
{"countryCode":"NF", "phoneCode":"672","country" :"Norfolk Islands (+672)"},
{"countryCode":"NP", "phoneCode":"670","country" :"Northern Marianas (+670)"},
{"countryCode":"NO", "phoneCode":"47","country" :"Norway (+47)"},
{"countryCode":"OM", "phoneCode":"968","country" :"Oman (+968)"},
{"countryCode":"PW", "phoneCode":"680","country" :"Palau (+680)"},
{"countryCode":"PA", "phoneCode":"507","country" :"Panama (+507)"},
{"countryCode":"PG", "phoneCode":"675","country" :"Papua New Guinea (+675)"},
{"countryCode":"PY", "phoneCode":"595","country" :"Paraguay (+595)"},
{"countryCode":"PE", "phoneCode":"51","country" :"Peru (+51)"},
{"countryCode":"PH", "phoneCode":"63","country" :"Philippines (+63)"},
{"countryCode":"PL", "phoneCode":"48","country" :"Poland (+48)"},
{"countryCode":"PT", "phoneCode":"351","country" :"Portugal (+351)"},
{"countryCode":"PR", "phoneCode":"1787","country" :"Puerto Rico (+1787)"},
{"countryCode":"QA", "phoneCode":"974","country" :"Qatar (+974)"},
{"countryCode":"RE", "phoneCode":"262","country" :"Reunion (+262)"},
{"countryCode":"RO", "phoneCode":"40","country" :"Romania (+40)"},
{"countryCode":"RU", "phoneCode":"7","country" :"Russia (+7)"},
{"countryCode":"RW", "phoneCode":"250","country" :"Rwanda (+250)"},
{"countryCode":"SM", "phoneCode":"378","country" :"San Marino (+378)"},
{"countryCode":"ST", "phoneCode":"239","country" :"Sao Tome &amp; Principe (+239)"},
{"countryCode":"SA", "phoneCode":"966","country" :"Saudi Arabia (+966)"},
{"countryCode":"SN", "phoneCode":"221","country" :"Senegal (+221)"},
{"countryCode":"CS", "phoneCode":"381","country" :"Serbia (+381)"},
{"countryCode":"SC", "phoneCode":"248","country" :"Seychelles (+248)"},
{"countryCode":"SL", "phoneCode":"232","country" :"Sierra Leone (+232)"},
{"countryCode":"SG", "phoneCode":"65","country" :"Singapore (+65)"},
{"countryCode":"SK", "phoneCode":"421","country" :"Slovak Republic (+421)"},
{"countryCode":"SI", "phoneCode":"386","country" :"Slovenia (+386)"},
{"countryCode":"SB", "phoneCode":"677","country" :"Solomon Islands (+677)"},
{"countryCode":"SO", "phoneCode":"252","country" :"Somalia (+252)"},
{"countryCode":"ZA", "phoneCode":"27","country" :"South Africa (+27)"},
{"countryCode":"ES", "phoneCode":"34","country" :"Spain (+34)"},
{"countryCode":"LK", "phoneCode":"94","country" :"Sri Lanka (+94)"},
{"countryCode":"SH", "phoneCode":"290","country" :"St. Helena (+290)"},
{"countryCode":"KN", "phoneCode":"1869","country" :"St. Kitts (+1869)"},
{"countryCode":"SC", "phoneCode":"1758","country" :"St. Lucia (+1758)"},
{"countryCode":"SD", "phoneCode":"249","country" :"Sudan (+249)"},
{"countryCode":"SR", "phoneCode":"597","country" :"Suriname (+597)"},
{"countryCode":"SZ", "phoneCode":"268","country" :"Swaziland (+268)"},
{"countryCode":"SE", "phoneCode":"46","country" :"Sweden (+46)"},
{"countryCode":"CH", "phoneCode":"41","country" :"Switzerland (+41)"},
{"countryCode":"SI", "phoneCode":"963","country" :"Syria (+963)"},
{"countryCode":"TW", "phoneCode":"886","country" :"Taiwan (+886)"},
{"countryCode":"TJ", "phoneCode":"7","country" :"Tajikstan (+7)"},
{"countryCode":"TH", "phoneCode":"66","country" :"Thailand (+66)"},
{"countryCode":"TG", "phoneCode":"228","country" :"Togo (+228)"},
{"countryCode":"TO", "phoneCode":"676","country" :"Tonga (+676)"},
{"countryCode":"TT", "phoneCode":"1868","country" :"Trinidad &amp; Tobago (+1868)"},
{"countryCode":"TN", "phoneCode":"216","country" :"Tunisia (+216)"},
{"countryCode":"TR", "phoneCode":"90","country" :"Turkey (+90)"},
{"countryCode":"TM", "phoneCode":"7","country" :"Turkmenistan (+7)"},
{"countryCode":"TM", "phoneCode":"993","country" :"Turkmenistan (+993)"},
{"countryCode":"TC", "phoneCode":"1649","country" :"Turks &amp; Caicos Islands (+1649)"},
{"countryCode":"TV", "phoneCode":"688","country" :"Tuvalu (+688)"},
{"countryCode":"UG", "phoneCode":"256","country" :"Uganda (+256)"},
{"countryCode":"GB", "phoneCode":"44","country" :"UK (+44)"},
{"countryCode":"UA", "phoneCode":"380","country" :"Ukraine (+380)"},
{"countryCode":"AE", "phoneCode":"971","country" :"United Arab Emirates (+971)"},
{"countryCode":"UY", "phoneCode":"598","country" :"Uruguay (+598)"},
{"countryCode":"US", "phoneCode":"1","country" :"USA (+1)"},
{"countryCode":"UZ", "phoneCode":"7","country" :"Uzbekistan (+7)"},
{"countryCode":"VU", "phoneCode":"678","country" :"Vanuatu (+678)"},
{"countryCode":"VA", "phoneCode":"379","country" :"Vatican City (+379)"},
{"countryCode":"VE", "phoneCode":"58","country" :"Venezuela (+58)"},
{"countryCode":"VN", "phoneCode":"84","country" :"Vietnam (+84)"},
{"countryCode":"VG", "phoneCode":"1284","country" :"Virgin Islands - British (+1284)"},
{"countryCode":"VI", "phoneCode":"1340","country" :"Virgin Islands - US (+1340)"},
{"countryCode":"WF", "phoneCode":"681","country" :"Wallis &amp; Futuna (+681)"},
{"countryCode":"YE", "phoneCode":"969","country" :"Yemen (North)(+969)"},
{"countryCode":"YE", "phoneCode":"967","country" :"Yemen (South)(+967)"},
{"countryCode":"ZM", "phoneCode":"260","country" :"Zambia (+260)"},
{"countryCode":"ZW", "phoneCode":"263","country" :"Zimbabwe (+263)"}]