import { StatusPowerbi } from "src/app/commons/enums/StatusColorsPowerbi.enum";

export interface ResponseInfoPowerbi {
  uuid?: string,
  name?: string,
  state: StatusPowerbi,
  received?: number,
  sent?: any,
  started?: number,
  rejected?: any,
  succeeded?: any,
  failed?: any,
  retried?: any,
  revoked?: any,
  args: string,
  kwargs?: string,
  eta?: any,
  expires?: any,
  retries?: number,
  worker?: string,
  result?: any,
  exception: string | null,
  timestamp?: number,
  runtime?: any,
  traceback?: any,
  exchange?: any,
  routing_key?: any,
  clock?: number,
  client?: any,
  root?: string,
  root_id?: string,
  parent?: any,
  parent_id?: any,
  children?: any[]
}
